### ISSUE TITLE
netconf-console --get-config Error

### ISSUE THREAD

**Issue by sezerb** [janlindblad/bookzone#3]
When we execute "netconf-console --get-config" on the terminal get the error given below:
_Traceback (most recent call last):
  File "/home/sezerb/Tools/confd-basic-7.4.1.linux.x86_64/./install//bin/netconf-console.py", line 1390, in <module>
    main(parser, o)
  File "/home/sezerb/Tools/confd-basic-7.4.1.linux.x86_64/./install//bin/netconf-console.py", line 1311, in main
    fd.close()
BrokenPipeError: [Errno 32] Broken pipe_

Please note that all the required packages are installed, we can connect to confd via ssh -already tested- and current python version 3.8.5 with our platform Ubunutu 20.04.1

**Comment by sherifmka2004** [comment]
sudo apt install libxml2-utils
I had same issue and was fixed by this command
